name: ceramic
publish_to: 'none'
version: 1.0.0+1
description: "My graphical implementation in Flutter of an IMEI validation app."
environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  luhny:
    git: https://github.com/angeldollface/luhny.dart
flutter:
  uses-material-design: true
  fonts:
    - family: Ostrich
      fonts:
        - asset: assets/fonts/Ostrich.ttf
    - family: MC
      fonts:
        - asset: assets/fonts/MC.ttf
